DROP TABLE IF EXISTS T_ACCOUNT;
CREATE TABLE T_ACCOUNT
(
	ID VARCHAR2(32) DEFAULT REPLACE(UUID(),'-','') COMMENT '主键' PRIMARY KEY,
	ACCOUNT VARCHAR2(32) NOT NULL COMMENT '账号',
	PASSWORD VARCHAR2(32) NOT NULL COMMENT '密码',
	STATUS TINYINT(2) NOT NULL DEFAULT '1' COMMENT '状态：1为有效，0为已删除',
	CREATE_TIME TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) COMMENT='登陆账号表';
DROP TABLE IF EXISTS T_USER;
CREATE TABLE T_USER (
	ID VARCHAR2(32) DEFAULT REPLACE(UUID(),'-','') COMMENT '主键' PRIMARY KEY,
	USERNAME VARCHAR(32) NOT NULL COMMENT '真实姓名',
	SEX TINYINT(2) NOT NULL DEFAULT '1' COMMENT '性别：1为男，0为女',
	TELEPHONE VARCHAR(32) COMMENT '电话号码',
	EMAIL VARCHAR(64) COMMENT '电子邮箱',
	ACCOUNT_ID VARCHAR(32) NOT NULL,
	CONSTRAINT FK_ACCOUNT_ID FOREIGN KEY(ACCOUNT_ID) REFERENCES T_ACCOUNT(ID) ON DELETE CASCADE
) COMMENT='用户信息表';
INSERT INTO T_ACCOUNT (ACCOUNT, PASSWORD) VALUES ('TEST','TEST123');
SELECT * FROM T_USER U;
SELECT * FROM T_ACCOUNT A LEFT JOIN T_USER U ON A.ID = U.ACCOUNT_ID;
